workspace:
  base: /go
  path: src/tx.18e.pub/p/plugins4rmmv

clone:
  ssh:
    image: appleboy/drone-ssh
    environment:
      - PLUGIN_HOST=tx.18e.pub
      - PLUGIN_USERNAME=ubuntu
    volumes:
      - /root/.ssh/id_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    script:
      - cd plugins4rmmv
      - git checkout .
      - git pull

pipeline:
  build:
    image: node:8.9.3
    #ports:
    #  - 8080:8080
    volumes:
      - /home/ubuntu/plugins4rmmv:/go/src/tx.18e.pub/p/plugins4rmmv
    commands:
    #  - npm install --silent
    #  - npm test
  run:
    image: appleboy/drone-ssh
    environment:
      - PLUGIN_HOST=tx.18e.pub
      - PLUGIN_USERNAME=ubuntu
    volumes:
      - /root/.ssh/id_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa
    script:
      - cd plugins4rmmv
      - docker-compose -f docker-compose.yml stop
      - docker-compose --workdir="/root/plugins4rmmv"  -f docker-compose.yml up -d

