let hot_Sprite_Enemy=()=>{
  class Sprite_Enemy extends Sprite_Tank{
    constructor(...args){
      super(...args)
      this.initialize(...args)
    }
    changeRoute(){
      this._routeTick=0
      this.look(Math.randomInt(4))
      this._desireRouteTick=Math.randomInt(40)+100
    }
    initialize(texture,frameWidth,frameHeight,hp){
      super.initialize(texture,frameWidth,frameHeight,hp)
      this.isStop=false
      this._desireMoveTick=30
      this._desireFireTick=60
      this._desireRouteTick=100
      this._routeTick=0
      this._desireDieTick=40
    }
    update(){
      super.update()
      if(this.state==Tank_State.Live&&!this.isStop){
        if(this.x<=this.width/2){
          this.x=this.width/2
          this.changeRoute()
        }
        if(this.x>=Graphics.boxWidth-this.width/2){
          this.x=Graphics.boxWidth-this.width/2
          this.changeRoute()
        }
        if(this.y>=Graphics.boxHeight-this.height/2){
          this.y=Graphics.boxHeight-this.height/2
          this.changeRoute()
        }
        if(this.y<=this.height/2){
          this.y=this.height/2
          this.changeRoute()
        }
        this._routeTick++
        if(this._routeTick>=this._desireRouteTick){
          this.changeRoute()
        }
        this.move()
      }
    }
  }
  window.Sprite_Enemy=Sprite_Enemy
}
module.exports=hot_Sprite_Enemy
